// The database's shape, as numbered steps. Each step runs once, in order, in
// one transaction under the desk's lock, and `schema_migrations` records it,
// so a fresh database and the live one end up the same. A change to the
// shape is a new step at the end; a step already on the live database is
// never edited.
//
// Times are ISO strings in TEXT columns, not timestamptz: an edit is refused
// when the updated_at it started from is no longer the row's, and that check
// compares the exact string the page was given. Flags are 0/1/NULL and JSON
// is TEXT, as they were in the Durable Object, so the store reads them the
// same way.

import { transaction } from './db.js';

// Every table that holds a site's details, as step 4 found them.
const DETAIL_TABLES = ['site_services', 'site_contacts', 'site_domains',
  'site_tiktok', 'site_linkedin', 'site_facebook', 'site_x', 'site_instagram'];

const NOW = `to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')`;

export const MIGRATIONS = [
  // 1. What the Durable Object held: the list, and going live.
  [
    `CREATE TABLE sites (
      id             TEXT PRIMARY KEY,
      name           TEXT NOT NULL,
      live_domain    TEXT,
      staging_domain TEXT,
      github_repo    TEXT,
      chat_url       TEXT,
      environment    TEXT,
      live_platform  TEXT CHECK (live_platform IN ('astro','wordpress','other','none')),
      astro_staging  SMALLINT CHECK (astro_staging IN (0,1)),
      domain_ours    SMALLINT CHECK (domain_ours IN (0,1)),
      needs_seo_ppc  SMALLINT CHECK (needs_seo_ppc IN (0,1)),
      notes          TEXT,
      created_at     TEXT NOT NULL,
      updated_at     TEXT NOT NULL
    )`,
    // Going live (golive-store.js): one row per site.
    `CREATE TABLE golive (
      site_id           TEXT PRIMARY KEY,
      state             TEXT NOT NULL,
      run_token         TEXT,            -- the run that holds the row; writes from any other run are ignored
      finished_token    TEXT,            -- the run that finished the row, so a finish tried again gets its answer
      zone_id           TEXT NOT NULL,
      zone_name         TEXT NOT NULL,
      worker            TEXT NOT NULL,   -- the staging Worker the hosts are attached to
      staging_host      TEXT NOT NULL,
      main_host         TEXT NOT NULL,
      hosts             TEXT NOT NULL,   -- JSON [{hostname, role}], main first
      saved_records     TEXT NOT NULL,   -- JSON: full DNS records to delete (the rollback), written before any delete
      saved_domains     TEXT NOT NULL,   -- JSON [{id, hostname, service}]: Custom Domains on other Workers, written before any detach
      redirect          TEXT,            -- JSON {from, to, ref} or null
      redirect_rule     TEXT,            -- JSON {ruleset_id, rule_id, ref} once created
      attached          TEXT NOT NULL,   -- JSON [{id, hostname, dns_id}] as each attach happens
      steps_done        TEXT NOT NULL,   -- JSON ['deleted:<record id>', 'detached:<domain id>', 'attached:<host>', 'redirect']
      mx_txt            TEXT NOT NULL,   -- JSON snapshot [{type, name, content, priority}] from the plan
      ssl_mode          TEXT,            -- the zone's SSL/TLS mode in the plan, for the gate 13 record
      previous_platform TEXT,
      restored          SMALLINT,        -- after a failed switch: 1 = everything was put back, 0 = not all of it
      checks            TEXT,            -- JSON: the last verification checks
      notes             TEXT,            -- JSON [string]: outcomes worth showing
      error             TEXT,
      acks              TEXT,            -- JSON: the acknowledgements given at start
      started_by        TEXT, started_at TEXT,
      switched_at       TEXT, verified_at TEXT,
      rolled_back_by    TEXT, rolled_back_at TEXT,
      updated_at        TEXT NOT NULL    -- refreshed by every step: the heartbeat
    )`,
    // BY DEFAULT, not ALWAYS: the copy from the Durable Object keeps each
    // entry's own number.
    `CREATE TABLE golive_log (
      seq     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      site_id TEXT NOT NULL,
      at      TEXT NOT NULL,
      who     TEXT,
      action  TEXT NOT NULL,   -- machine name, e.g. 'switch-started', 'record-deleted'
      text    TEXT NOT NULL,   -- one plain sentence the page shows
      detail  TEXT             -- JSON
    )`,
    'CREATE INDEX golive_log_site ON golive_log (site_id, seq)',
    `CREATE TABLE golive_checks (
      site_id      TEXT PRIMARY KEY,
      plan_hash    TEXT NOT NULL,
      checks_hash  TEXT NOT NULL DEFAULT '',  -- the Cloudflare checks the person read (checksDigest)
      include_pair SMALLINT NOT NULL,
      ready        SMALLINT NOT NULL,
      acks         TEXT NOT NULL,     -- JSON [{id, label}] the check requires
      checked_by   TEXT NOT NULL,
      checked_at   TEXT NOT NULL
    )`,
    // Facts about the database itself, such as when the Durable Object's
    // rows were copied in.
    `CREATE TABLE desk_meta (
      key   TEXT PRIMARY KEY,
      value TEXT NOT NULL
    )`,
  ],

  // 2. Everything else about a site, and the history of every change.
  [
    // The accounts and resources a site uses. `kind` is checked by
    // details.js, not here, so a new kind needs no migration. Never a
    // password or key: the desk is behind one shared key.
    `CREATE TABLE site_services (
      id         TEXT PRIMARY KEY,
      site_id    TEXT NOT NULL REFERENCES sites (id) ON DELETE CASCADE,
      kind       TEXT NOT NULL,
      identifier TEXT,
      url        TEXT,
      account    TEXT,
      notes      TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
    'CREATE INDEX site_services_site ON site_services (site_id)',
    `CREATE TABLE site_contacts (
      id         TEXT PRIMARY KEY,
      site_id    TEXT NOT NULL REFERENCES sites (id) ON DELETE CASCADE,
      name       TEXT NOT NULL,
      role       TEXT,
      email      TEXT,
      phone      TEXT,
      notes      TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
    'CREATE INDEX site_contacts_site ON site_contacts (site_id)',
    `CREATE TABLE site_domains (
      id                TEXT PRIMARY KEY,
      site_id           TEXT NOT NULL REFERENCES sites (id) ON DELETE CASCADE,
      hostname          TEXT NOT NULL,
      role              TEXT NOT NULL CHECK (role IN ('live','staging','image','redirect','old','other')),
      registrar         TEXT,
      dns_on_cloudflare SMALLINT CHECK (dns_on_cloudflare IN (0,1)),
      renews_on         TEXT CHECK (renews_on ~ '^\\d{4}-\\d{2}-\\d{2}$'),
      notes             TEXT,
      created_at        TEXT NOT NULL,
      updated_at        TEXT NOT NULL,
      UNIQUE (site_id, hostname)
    )`,
    'CREATE INDEX site_domains_site ON site_domains (site_id)',
    // One row per field changed, and one per row added or removed (its
    // fields as JSON). No foreign key: a deleted site's history stays.
    `CREATE TABLE history (
      id        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      at        TEXT NOT NULL DEFAULT ${NOW},
      who       TEXT,
      site_id   TEXT NOT NULL,
      item      TEXT NOT NULL,
      item_id   TEXT NOT NULL,
      action    TEXT NOT NULL CHECK (action IN ('added','changed','removed')),
      field     TEXT,
      old_value TEXT,
      new_value TEXT
    )`,
    'CREATE INDEX history_site ON history (site_id, id)',
    // The database writes the history itself, so no change can skip it,
    // whoever makes it. `desk.who` is set by a go-live run; `desk.importing`
    // by the copy from the Durable Object, which is not a change.
    `CREATE FUNCTION desk_history() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
      item    TEXT := TG_ARGV[0];
      who     TEXT := NULLIF(current_setting('desk.who', true), '');
      skip    TEXT[] := ARRAY['id', 'site_id', 'created_at', 'updated_at'];
      old_row JSONB;
      new_row JSONB;
      k       TEXT;
    BEGIN
      IF current_setting('desk.importing', true) = 'on' THEN
        RETURN NULL;
      END IF;
      IF TG_OP <> 'INSERT' THEN old_row := to_jsonb(OLD); END IF;
      IF TG_OP <> 'DELETE' THEN new_row := to_jsonb(NEW); END IF;
      IF TG_OP = 'INSERT' THEN
        INSERT INTO history (who, site_id, item, item_id, action, new_value)
        VALUES (who, COALESCE(new_row->>'site_id', new_row->>'id'), item, new_row->>'id', 'added',
                jsonb_strip_nulls(new_row - skip)::text);
      ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO history (who, site_id, item, item_id, action, old_value)
        VALUES (who, COALESCE(old_row->>'site_id', old_row->>'id'), item, old_row->>'id', 'removed',
                jsonb_strip_nulls(old_row - skip)::text);
      ELSE
        FOR k IN SELECT jsonb_object_keys(new_row - skip) LOOP
          IF (old_row->k) IS DISTINCT FROM (new_row->k) THEN
            INSERT INTO history (who, site_id, item, item_id, action, field, old_value, new_value)
            VALUES (who, COALESCE(new_row->>'site_id', new_row->>'id'), item, new_row->>'id', 'changed', k,
                    old_row->>k, new_row->>k);
          END IF;
        END LOOP;
      END IF;
      RETURN NULL;
    END
    $$`,
    `CREATE TRIGGER sites_history AFTER INSERT OR UPDATE OR DELETE ON sites
      FOR EACH ROW EXECUTE FUNCTION desk_history('site')`,
    `CREATE TRIGGER site_services_history AFTER INSERT OR UPDATE OR DELETE ON site_services
      FOR EACH ROW EXECUTE FUNCTION desk_history('service')`,
    `CREATE TRIGGER site_contacts_history AFTER INSERT OR UPDATE OR DELETE ON site_contacts
      FOR EACH ROW EXECUTE FUNCTION desk_history('contact')`,
    `CREATE TRIGGER site_domains_history AFTER INSERT OR UPDATE OR DELETE ON site_domains
      FOR EACH ROW EXECUTE FUNCTION desk_history('domain')`,
  ],

  // 3. A table for each social media platform: the site's handle there, its
  // profile link, whose login it is under, and notes. The five names are
  // written out, not read from details.js: a step never changes once it has
  // run, and a new platform is a step of its own.
  ['tiktok', 'linkedin', 'facebook', 'x', 'instagram'].flatMap((platform) => [
    `CREATE TABLE site_${platform} (
      id         TEXT PRIMARY KEY,
      site_id    TEXT NOT NULL REFERENCES sites (id) ON DELETE CASCADE,
      handle     TEXT,
      url        TEXT NOT NULL,
      account    TEXT,
      notes      TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      UNIQUE (site_id, url)
    )`,
    `CREATE INDEX site_${platform}_site ON site_${platform} (site_id)`,
    `CREATE TRIGGER site_${platform}_history AFTER INSERT OR UPDATE OR DELETE ON site_${platform}
      FOR EACH ROW EXECUTE FUNCTION desk_history('${platform}')`,
  ]),


  // 4. Ids a person can read: 0001, 0002, 0003, in the order rows were
  // made, each table counting on its own, and past 9999 simply 10000. Every
  // row already here is renumbered, and everything that names it (a site's
  // details, its go-live record and log, the history) follows. A renumber is
  // not a change to the site, so the history triggers stand aside for it.
  // From here on store.js takes each new id from the table's own counter.
  [
    "SELECT set_config('desk.importing', 'on', true)",
    // A site's details follow its id from now on, whatever changes it.
    ...DETAIL_TABLES.map((t) => `ALTER TABLE ${t}
      DROP CONSTRAINT ${t}_site_id_fkey,
      ADD CONSTRAINT ${t}_site_id_fkey FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE CASCADE ON UPDATE CASCADE`),
    ...['sites', ...DETAIL_TABLES].flatMap((t) => [
      `CREATE TEMP TABLE ${t}_renumber ON COMMIT DROP AS
        SELECT id AS old, CASE WHEN n < 10000 THEN lpad(n::text, 4, '0') ELSE n::text END AS new
        FROM (SELECT id, row_number() OVER (ORDER BY created_at, id) AS n FROM ${t}) AS numbered`,
      `UPDATE ${t} SET id = r.new FROM ${t}_renumber r WHERE ${t}.id = r.old`,
      `CREATE SEQUENCE ${t}_number`,
      `SELECT setval('${t}_number', GREATEST(count(*), 1), count(*) > 0) FROM ${t}`,
    ]),
    ...['golive', 'golive_log', 'golive_checks', 'history'].map((t) =>
      `UPDATE ${t} SET site_id = r.new FROM sites_renumber r WHERE ${t}.site_id = r.old`),
    ...Object.entries({ site: 'sites', service: 'site_services', contact: 'site_contacts', domain: 'site_domains',
      tiktok: 'site_tiktok', linkedin: 'site_linkedin', facebook: 'site_facebook', x: 'site_x', instagram: 'site_instagram' })
      .map(([item, t]) => `UPDATE history SET item_id = r.new FROM ${t}_renumber r WHERE history.item = '${item}' AND history.item_id = r.old`),
  ],

  // 5. The client form (public/client-form.html). Its job list: one row per
  // URL, with a tick for each piece of work it needs. And the form's own
  // options, once per site. Both count their ids as step 4 set up, and the
  // history records them like any other detail.
  [
    `CREATE TABLE site_jobs (
      id          TEXT PRIMARY KEY,
      site_id     TEXT NOT NULL REFERENCES sites (id) ON DELETE CASCADE ON UPDATE CASCADE,
      url         TEXT NOT NULL,
      clone       SMALLINT CHECK (clone IN (0,1)),
      database_b2 SMALLINT CHECK (database_b2 IN (0,1)),   -- database / Backblaze B2
      seo_ppc     SMALLINT CHECK (seo_ppc IN (0,1)),
      live        SMALLINT CHECK (live IN (0,1)),
      notes       TEXT,
      created_at  TEXT NOT NULL,
      updated_at  TEXT NOT NULL,
      UNIQUE (site_id, url)
    )`,
    'CREATE INDEX site_jobs_site ON site_jobs (site_id)',
    'CREATE SEQUENCE site_jobs_number',
    `CREATE TRIGGER site_jobs_history AFTER INSERT OR UPDATE OR DELETE ON site_jobs
      FOR EACH ROW EXECUTE FUNCTION desk_history('job')`,
    `CREATE TABLE client_forms (
      id                  TEXT PRIMARY KEY,
      site_id             TEXT NOT NULL UNIQUE REFERENCES sites (id) ON DELETE CASCADE ON UPDATE CASCADE,
      notify_rep          SMALLINT NOT NULL CHECK (notify_rep IN (0,1)),
      notify_client       SMALLINT NOT NULL CHECK (notify_client IN (0,1)),
      competitor_analysis SMALLINT NOT NULL CHECK (competitor_analysis IN (0,1)),
      created_at          TEXT NOT NULL,
      updated_at          TEXT NOT NULL
    )`,
    'CREATE SEQUENCE client_forms_number',
    `CREATE TRIGGER client_forms_history AFTER INSERT OR UPDATE OR DELETE ON client_forms
      FOR EACH ROW EXECUTE FUNCTION desk_history('client_form')`,
  ],

  // 6. A service's password, encrypted (secrets.js): the ciphertext only,
  // never the password. A table of its own, with no history trigger, so the
  // ciphertext is never copied into the history either; store.js writes the
  // history line itself, saying only that a password was set, changed or
  // removed. It goes with its service.
  [
    `CREATE TABLE service_passwords (
      service_id TEXT PRIMARY KEY REFERENCES site_services (id) ON DELETE CASCADE ON UPDATE CASCADE,
      site_id    TEXT NOT NULL REFERENCES sites (id) ON DELETE CASCADE ON UPDATE CASCADE,
      ciphertext TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
    'CREATE INDEX service_passwords_site ON service_passwords (site_id)',
  ],
];

// Brings the database up to the last step (or to `upTo`, for a test that
// needs the shape as it was). Safe to call from every request at once: the
// lock makes the others wait, and they then find nothing to do.
export async function migrate(connect, { upTo = MIGRATIONS.length } = {}) {
  return transaction(connect, async (tx) => {
    await tx.run(`CREATE TABLE IF NOT EXISTS schema_migrations (
      version    INTEGER PRIMARY KEY,
      applied_at TEXT NOT NULL
    )`);
    const done = (await tx.row('SELECT COALESCE(MAX(version), 0) AS v FROM schema_migrations')).v;
    for (let v = done + 1; v <= upTo; v++) {
      for (const statement of MIGRATIONS[v - 1]) await tx.run(statement);
      await tx.run('INSERT INTO schema_migrations (version, applied_at) VALUES (?, ?)', v, new Date().toISOString());
    }
    return MIGRATIONS.length;
  }, { write: true });
}
